<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />


        <title><?php echo 'Logger' ?></title>
        <link rel="stylesheet" href="/Content/plugins/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="/Content/plugins/ionicons/css/ionicons.min.css">
        <link rel="stylesheet" href="Content/dist/css/adminlte.min.css">
        <link href="/Content/Custom/googlefontcss.css" rel="stylesheet">
        <link href="/Content/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <script src="/Content/plugins/jquery/jquery.min.js"></script>
        <script src="/Content/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script src="/Content/plugins/fastclick/fastclick.js"></script>
        <script src="Content/dist/js/adminlte.min.js"></script>
        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet" />




    </head>

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <nav class="main-header navbar navbar-expand navbar-fixed-top bg-white navbar-light border-bottom elevation-1">
                  <!-- Left navbar links -->
          <ul class="navbar-nav">
            <li class="nav-item">
             <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
            </li>
          </ul>
          <form action="/search" method="get" id="search-form">
            <input class="nav-item" type="text" placeholder="Search for...." name="query" value="<?php echo $query;?>"
                     aria-label="Search"/>
              <select name="statusValue" class="ml-2">
                <option value=">=0">select status code</option>
                <option value="=200">200</option>
                <option value="=302">302</option>
                <option value="=400">400</option>
                <option value="=403">403</option>
                <option value="=404">404</option>
                <option value="=405">405</option>
                <option value="=429">429</option>
                <option value="=501">501</option>
                <option value="=503">503</option>
                <option value=">=400">>=400</option>
              </select>
                <button type="submit" class="nav-item">search</button>
            </form>
    </nav>
  <!-- /.navbar -->

  <aside class="main-sidebar sidebar-dark-info elevation-4">
    <!-- Brand Logo -->
        <a class="brand-link">
            <img src="Content/Images/unipun.png" class="brand-image img elevation-3" />
            <span class="brand-text font-weight-heavy ml-2" style="color: white; font-size: large" title="Savitribai Phule Pune University">Live Logger
            </span>

        </a>

  <!-- Sidebar -->
        <div class="sidebar">
                            <!-- Sidebar Menu -->
            <nav class="mt-2">
              <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                  <li class="nav-item mt-3">
                      <a class="nav-link elevation-2" style="color: #fff; background-color: rgba(255,255,255,.1)" href="/">
                          <span data-feather="home"></span>
                          Dashboard <span class="sr-only">(current)</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="/request">
                          <span data-feather="file"></span>
                          Requests
                      </a>
                  </li>
                  <li class="nav-item <?php echo $currentPage === 'ping' ? 'active' : '' ?>">
                      <a class="nav-link" href="/ping">
                          <span data-feather="file"></span>
                          ping
                      </a>
                  </li>
                  <li class="nav-item mt-4 <?php echo $currentPage === 'change-password' ? 'active' : '' ?>">
                      <a class="nav-link" href="/change-password">
                          <span data-feather="file"></span>
                          Change Password
                      </a>
                  </li>
                </ul>
              </nav>
              <!-- /.sidebar-menu -->
          </div>
          <!-- /.sidebar -->
        </aside>

<!-- Contains page content -->
      <div>
        <div class="content-wrapper">
          <section class="content-header">
              <div class="container-fluid">
              </div>
          </section>
          <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 mt-5">
                      <div class="card card-info card-outline elevation-2">

                          <div class="card-header">
                              <ul class="nav nav-pills">
                                  <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#InstEng"><small style="font-size: medium; font-weight: 600">Tables</small></a></li>
                                  <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#InstMar"><small style="font-size: medium; font-weight: 600">Graphs</small></a></li>
                              </ul>
                          </div>

                          <div class="card-body">
                              <div class="col-md-12">
                                  <div class="row">
                                      <div class="tab-content">
                                        <div id="InstEng" class="active tab-pane" style="padding-top: 1%">


                                            <h1 class="h1">Dashbord</h1>


                                              <div style="float: left" name="table">

                                                  <table  class="table table-striped table-sm" id="datatable" name="datatable">
                                                      <thead>
                                                          <tr> <th>date(hour wise)</th>
                                                              <th>total entries</th>
                                                          </tr></thead>
                                                      <tbody>
                                                          <?php foreach($result as $xx) { ?>
                                                      <tr>
                                                          <td><?php echo $xx['x'] ?></td>
                                                          <td><?php echo $xx['y'] ?></td>
                                                      </tr>
                                                      <?php } ?>
                                                        </tbody>
                                                    </table>
                                              


                                                </div>
                                              </div>
                                            <div id="InstMar" class="tab-pane" style="padding-top: 1%">
                                              <h1>this is the page with graph and insights </h1>
                                              <div id="chart_div" name="chart" style="width: 140%; min-height: 450px;"></div>
                                              <div id="chart_div2" name="chart" ></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </section>
      </div>
  </div>
<!-- /.content-wrapper -->

<footer class="main-footer">
    <span style="font-weight: 600">Copyright !yep thats right! do not copy this &copy;Logger@GCi. All rights are not reserved.</span>
    <div class="float-right">
         <a href="#" class="btn" style="background-color:white"></a>
    </div>
</footer>







</div>
    <!-- ./wrapper -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['date', 'total', 'sucess', 'failed'],
          <?php foreach($result2 as $xx) { ?>
          ['<?php echo $xx['aa'] ?>',  <?php echo $xx['bb'] ?>, <?php echo $xx['cc'] ?>, <?php echo $xx['dd'] ?>],
        <?php } ?>
        ]);

        var options = {
          title: 'Company Performance',
          hAxis: {title: 'Year',  titleTextStyle: {color: '#333'}},
          vAxis: {minValue: 0}
     
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
        chart.draw(data, options);


      }
    </script>

</body>


</html>
