<?php include_once __DIR__ . '/./../layout/header.phtml'; ?>

<style type="text/css">
    html,
    body {
      height: 100%;
    }

    body {
      display: -ms-flexbox;
      display: flex;
      -ms-flex-align: center;
      align-items: center;
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #f5f5f5;
    }
</style>

<div style="margin: 0 auto; text-align: center;">
    <form class="form-signin" method="post">
        <img class="mb-4" src="/images/gci-network.png" alt="GCI Network" />
        <h1 class="h3 mb-3 font-weight-normal">Sign up here</h1>
        <?php
            if(!empty($error['message'])) {
                echo sprintf('<div class="alert alert-%s" role="alert">%s</div>', $error['error'] ? 'danger' : 'success', $error['message']);
            }
        ?>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus name="email" value="<?php echo $email ?>" />
        <label for="firstName" class="sr-only">First Name</label>
        <input type="text" id="firstName" class="form-control" placeholder="First name" required name="firstName" value="<?php echo $firstName ?>" />
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password" />
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
        <a href="/" class="btn btn-lg btn-default btn-block">Sign in</a>
        <p class="mt-5 mb-3 text-muted">&copy; 2010 - <?php echo date('Y') ?></p>
    </form>
</div>
<?php include_once __DIR__ . '/./../layout/footer.phtml'; ?>