<!DOCTYPE html>
<html>

<!-- Mirrored from sps.unipune.ac.in/app/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 19 Nov 2019 05:54:57 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="Content/Images/unipun.png" />
    <title>Not AnyMore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="Content/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="Content/plugins/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="Content/dist/css/adminlte.min.css">
    <link href="Content/Custom/googlefontcss.css" rel="stylesheet">
    <link href="Content/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <script src="Content/plugins/jquery/jquery.min.js"></script>
    <script src="Content/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="Content/plugins/fastclick/fastclick.js"></script>
    <script src="Content/dist/js/adminlte.min.js"></script>
    

    
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-fixed-top bg-white navbar-light border-bottom elevation-1">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                </li>
            </ul>
            
			<input class="ml-5" type="text" placeholder="Search for...." name="query" value="<?php echo $query;?>"
               aria-label="Search"/>
			   <select name="statusValue" class="ml-2">
    <option value=">=0">select status code</option>
                <option value="=200">200</option>
                <option value="=302">302</option>
                <option value="=400">400</option>
                <option value="=403">403</option>
                <option value="=404">404</option>
                <option value="=405">405</option>
                <option value="=429">429</option>
                <option value="=501">501</option>
                <option value="=503">503</option>
                <option value=">=400">>=400</option>                
            </select>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-info elevation-4">
            <!-- Brand Logo -->
            <a class="brand-link">
                <img src="Content/Images/unipun.png" class="brand-image img-circle elevation-3" />
                <span class="brand-text font-weight-heavy ml-2" style="color: white; font-size: large" title="Savitribai Phule Pune University">Live Logger
                </span>
                
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                        <li class="nav-item mt-3">
                            <a class="nav-link elevation-2" style="color: #fff; background-color: rgba(255,255,255,.1)">
                                <i class="fa fa-user-o nav-icon"></i>
                                <p>
                                    Student
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="index-2.html" class="nav-link active">
                                <i class="fa fa-home nav-icon"></i>
                                <p>Home</p>
                            </a>
                        </li>
                        <li class="nav-item">

                            <a href="http://sim.unipune.ac.in/sim_app/Account/CreateAccount" class="nav-link">
                                <i class="fa fa-address-book-o nav-icon"></i>
                                <p>Create Account</p>
                            </a>
                        </li>
                        <li class="nav-item">

                            <a href="http://sim.unipune.ac.in/sim_app/Login/Login" class="nav-link">
                                <i class="fa fa-sign-in nav-icon"></i>
                                <p>Log In</p>
                            </a>
                        </li>

                        <li class="nav-item mt-4">
                            <a class="nav-link elevation-2" style="color: #fff; background-color: rgba(255,255,255,.1)">
                                <i class="nav-icon fa fa-user-o"></i>
                                <p>
                                    College
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="College/CollegeLogin/CollegeLogin.html" class="nav-link">
                                <i class="fa fa-sign-in nav-icon"></i>
                                <p>Log In</p>
                            </a>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Contains page content -->
        <div>
            


<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 mt-5">
                    <div class="card card-info card-outline elevation-2">

                        <div class="card-header">
                            <ul class="nav nav-pills">
                                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#InstEng"><small style="font-size: medium; font-weight: 600">Instructions</small></a></li>
                                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#InstMar"><small style="font-size: medium; font-weight: 600">सूचना</small></a></li>
                            </ul>
                        </div>

                        <div class="card-body">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="tab-content">
                                        <div id="InstEng" class="active tab-pane" style="padding-top: 1%">
                                            
                                            
                                            <p><span style="font-weight: 600">Every student who wish to apply for Online Exam Form (Regular/External) need to be registered on Student Profile System (SPS).</span></p>
                                            <strong>Features of Student Profile System (SPS)</strong>
                                            <ul>
                                                <li>This is one-time/permanent profile management system for student.</li>
                                                <li>Once registered student will be able to use same account across multiple online applications of university through out his course. i.e. Student will be able to use this account from first year of course to degree.</li>
                                                <li>No duplicate accounts is allowed on same <span style="font-weight: 600">Aadhaar number</span>(For Indian Students)/<span style="font-weight: 600">Passport Number</span>(For International Students), <span style="font-weight: 600">Email ID</span> and <span style="font-weight: 600">Mobile Number</span>.</li>
                                                <li>Only one account per student is allowed.</li>
                                            </ul>
                                            <strong>Instructions for Creating Account On Student Profile System (SPS)</strong><br />
                                            &nbsp;&nbsp;&nbsp; Before creating account on SPS you need to have following things with you
                                            
                                            <ul>
                                                <li>Valid <span style="font-weight: 600">Aadhaar Number</span> (Only For Indian Students).</li>
                                                <li>Valid <span style="font-weight: 600">Passport Number</span> (Only For International Students).</li>
                                                <li>Valid <span style="font-weight: 600">Email ID</span>. An OTP will be sent on your email id for verify.</li>
                                                <li>Valid <span style="font-weight: 600">Mobile Number</span>. An OTP will be sent on your mobile number for verify.</li>
                                            </ul>

                                            <strong>Instructions for Creating Profile On Student Profile System (SPS)</strong><br />
                                            &nbsp;&nbsp;&nbsp; Before creating profile on SPS you need to have following things with you
                                           
                                            <ul>
                                                <li><span style="font-weight: 600">PUNCODE:</span> Unique 10 digit code assigned to each college by university. You can search it from your login.</li>
                                                <li><span style="font-weight: 600">Eligibility Number:</span> Every student gets this number when his eligibility is done by college in eligibility online portal. This number is must for creating profile. Please contact your college to get this number.<br />
                                                    <span style="font-weight: 600">This number is not applicable to International Students.</span>
                                                </li>
                                                <li><span style="font-weight: 600">PRN:</span> (Permanent Registration Number) This number is allotted to a student when he/she first appears for university exam.  This number is must for creating profile. This number is printed on student's university mark sheet.</li>
                                                <li><span style="font-weight: 600">Previous Exam Marksheet:</span> Keep Previous Exam Marksheet with you while creating profile.</li>
                                                <li><span style="font-weight: 600">Photo(Passport Size): </span>Scan copy of passport size photo in JPEG format and file size must be less than 300KB.</li>
                                                <li><span style="font-weight: 600">Signature: </span>Scan copy of your signature in JPEG format and file size must be less than 50KB.</li>
                                            </ul>
                                            <p><span style="font-weight: 600">Based upon data in your profile your exam form will be made available to you, so please provide accurate information in profile.</span></p>
                                            <strong>Steps To Create Profile</strong>
                                            <ol>
                                                <li><span style="font-weight: 600">Create Account</span></li>
                                                <li><span style="font-weight: 600">Login</span></li>
                                                <li><span style="font-weight: 600">Enroll for the Course </span></li>
                                                <li><span style="font-weight: 600">Fill Personal Information </span></li>
                                            </ol>
                                            <p><span style="font-weight: 600">After completing above four steps your profile will be complete and you can fill exam form by clicking</span><strong> Exam Form </strong><span style="font-weight: 600">button from dashboard.</span></p>
                                        </div>

                                        <div id="InstMar" class="tab-pane" style="padding-top: 1%">
                                             <p><span style="font-weight: 600">Student Profile System (SPS) वर ऑनलाईन परीक्षेचा फॉर्म (Regular/External) साठी अर्ज करण्याची इच्छा असलेल्या प्रत्येक विद्यार्थ्याला नोंदणी करणे आवश्यक आहे.</span></p>
                                            <strong>Student Profile System (SPS) ची वैशिष्ट्ये</strong>
                                            <ul>
                                                <li>विद्यार्थ्यांने या प्रणाली मध्ये एकदाच प्रोफाइल बनवायचे आहे.</li>
                                                <li>एकदा प्रोफाइल बनवले की तो विद्यापीठाच्या विविध ऑनलाइन ऍप्लिकेशनमध्ये हीच प्रोफाइल वापरण्यास सक्षम असेल. अर्थात विद्यार्थी हे प्रोफाइल आपल्या अभ्यासक्रमाच्या पहिल्या वर्षापासून पदवीपर्यंत वापरू शकतो.</li>
                                                <li>Account बनवताना <span style="font-weight: 600">आधार क्रमांक</span> (भारतीय विद्यार्थ्यांसाठी लागू) / <span style="font-weight: 600">पासपोर्ट क्रमांक</span> (आंतरराष्ट्रीय विद्यार्थ्यांसाठी लागू), <span style="font-weight: 600">ईमेल आयडी</span> आणि <span style="font-weight: 600">मोबाइल नंबर</span> डुप्लिकेट नसावेत.</li>
                                                <li>एका विद्यार्थ्याचे केवळ एकच Account असावे.</li>
                                            </ul>
                                            <strong>Student Profile System (SPS)वर Account तयार करण्यासाठी सूचना</strong><br />
                                            &nbsp;&nbsp;&nbsp; SPS वर Account तयार करण्यापूर्वी आपल्याबरोबर खालील गोष्टी असणे आवश्यक आहे.
                                            <ul>
                                                <li>वैध <span style="font-weight: 600">आधार क्रमांक</span> (केवळ भारतीय विद्यार्थ्यांसाठी लागू).</li>
                                                <li>वैध <span style="font-weight: 600">पासपोर्ट क्रमांक</span> (केवळ आंतरराष्ट्रीय विद्यार्थ्यांसाठी लागू).</li>
                                                <li>वैध <span style="font-weight: 600">ई-मेल आयडी</span>. ईमेल verify करण्यासाठी आपल्या ईमेलवर एक OTP पाठविला जाईल.</li>
                                                <li>वैध <span style="font-weight: 600">मोबाइल नंबर</span>. मोबाईल verify करण्यासाठी आपल्या मोबाईल नंबरवर एक OTP पाठविला जाईल.</li>
                                            </ul> 
                                            <strong>Student Profile System (SPS) वर प्रोफाइल तयार करण्यासाठी सूचना</strong><br />
                                            &nbsp;&nbsp;&nbsp; SPS वर प्रोफाइल तयार करण्यापूर्वी आपल्याबरोबर खालील गोष्टी असणे आवश्यक आहे. 
                                            <ul>
                                                <li><span style="font-weight: 600">PUNCODE:</span> विद्यापीठाने प्रत्येक कॉलेजला एक 10 अंकी कोड दिला आहे. आपण आपल्या Login मधून तो शोधू शकता.</li>
                                                <li><span style="font-weight: 600">पात्रता क्रमांक:</span> महाविद्यालय आपल्या प्रत्येक विध्यार्थ्याची पात्रता ही ऑनलाइन पोर्टलमध्ये करते तेव्हा प्रत्येक विद्यार्थ्याला हा क्रमांक प्राप्त होतो. प्रोफाइल तयार करण्यासाठी हा नंबर आवश्यक आहे. हा नंबर मिळविण्यासाठी आपल्या महाविद्यालयाशी संपर्क साधा.<br />
                                                    <span style="font-weight: 600">हा पात्रता क्रमांक आंतरराष्ट्रीय विद्यार्थ्यांसाठी लागू होत नाही.</span>
                                                </li>
                                                <li><span style="font-weight: 600">PRN:</span> (कायमस्वरूपी नोंदणी क्रमांक) हा क्रमांक विद्यार्थ्याला दिला जातो जेव्हा तो विद्यापीठाची परीक्षा पहिल्यांदा देतो. प्रोफाइल तयार करण्यासाठी हा क्रमांक आवश्यक आहे. हा क्रमांक विद्यार्थ्यांच्या मार्कशीटवर छापलेला असतो.</li>
                                                <li><span style="font-weight: 600">मागील परीक्षेचे मार्कशीट:</span> प्रोफाइल तयार करताना मागील परीक्षेचे मार्कशीट स्वतःबरोबर ठेवा.</li>
                                                
                                                <li><span style="font-weight: 600">फोटो (पासपोर्ट आकाराचा):</span> JPEG स्वरूपात पासपोर्ट आकाराचा फोटो स्कॅन करा आणि फोटोचा आकार 300KB पेक्षा कमी असावा.</li>
                                                <li><span style="font-weight: 600">स्वाक्षरी फोटो:</span> JPEG स्वरुपात आपल्या स्वाक्षरीची फोटो स्कॅन करा आणि फोटोचा आकार 50KB पेक्षा कमी असावा.</li>
                                            </ul>
                                            <p><span style="font-weight: 600">आपल्या प्रोफाइलमधील माहितीच्या आधारावर आपल्याला परीक्षा फॉर्म उपलब्ध करून दिला जाईल, म्हणून कृपया प्रोफाइलमध्ये अचूक माहिती प्रदान करा.</span></p>
                                            <strong>प्रोफाइल तयार करण्याचे टप्पे</strong>
                                            <ol>
                                                <li>Account तयार करा</li>
                                                <li>Login करा</li>
                                                <li>कोर्ससाठी नोंदणी करा</li>
                                                <li>वैयक्तिक माहिती भरा</li>
                                            </ol>
                                            <p><span style="font-weight: 600">वरील चार टप्पे पूर्ण केल्यानंतर आपले प्रोफाइल पूर्ण होईल आणि आपण डॅशबोर्डवरील Exam Form बटनावर क्लिक करून परीक्षा फॉर्म भरू शकता.</span></p>
                                        </div> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 mt-2">
                    <div class="card card-info card-outline elevation-2">
                        <div class="card-header elevation-1" style="text-align: center">
                            <small style="font-size: larger; font-weight: 600">Student</small>
                        </div>
                        <div class="card-body">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6" style="text-align: center">
                                        <a href="http://sim.unipune.ac.in/sim_app/Account/CreateAccount" class="btn btn-info mb-1 elevation-1" style="width: 80%">Create Account</a>
                                    </div>
                                    <div class="col-md-6" style="text-align: center">
                                        <a href="http://sim.unipune.ac.in/sim_app/Login/Login" class="btn btn-info mb-1 elevation-1" style="width: 80%">Log In</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mt-2">
                    <div class="card card-info card-outline elevation-2">
                        <div class="card-header elevation-1" style="text-align: center">
                            <small style="font-size: larger; font-weight: 600">College</small>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12" style="text-align: center">
                                    <a href="College/CollegeLogin/CollegeLogin.html" class="btn btn-info mb-1 elevation-1" style="width: 80%">Log In</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
</div>








        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <span style="font-weight: 600">Copyright &copy; 2018 Savitribai Phule Pune University. All rights reserved.</span>
            <div class="float-right">
                 <a href="Support/SupportLogin/SupportLogin.html" class="btn" style="background-color:white"></a>
            </div>
        </footer>

    </div>
    <!-- ./wrapper -->

</body>

<!-- Mirrored from sps.unipune.ac.in/app/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 19 Nov 2019 05:55:05 GMT -->
</html>

