<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" href="/favicon.ico" />

        <title># <?php echo $requestId ?></title>

        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet" />

        <!-- Custom styles for this template -->
        <link href="/css/style.css" rel="stylesheet">
        
        
    </head>

    <body>

    
<?php include_once __DIR__ . '/./../layout/top-header.phtml'; ?>
    
    <div class="container-fluid">
    <div class="row">
        <?php include_once __DIR__ . '/./../layout/sidebar.phtml' ?>
      
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" >
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">#id:<?php echo $requestId ?></h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                  
                    <div class="btn-group mr-2">
                        <a class="btn btn-sm btn-outline-secondary" id="demo" href="mail.php">share</a>
                        
                        <button class="btn btn-sm btn-outline-secondary" id="button1" onclick="CopyToClipboard('div1')">Click to copy</button>
                    </div>
                    
                </div>
            </div>
     
     <div id="div1">
         <style type="text/css">
                .followup-view {margin-bottom: 30px;                }
            </style>
            
            <div class="row followup-view" id="dvData">
                <div class="col-sm-6">
                    <label>Request Uuid: </label>
                    <p><?php echo $request['requestUuid'] ?></p>
                </div>
                <div class="col-sm-6">
                    <label>Request Url: </label>
                    <p><?php echo $request['requestUrl'] ?></p>
                </div>
                <div class="col-sm-3">
                    <label>Request Method: </label>
                    <p><?php echo $request['requestMethod'] ?></p>
                </div>
                <div class="col-sm-3">
                    <label>Source: </label>
                    <p><?php echo $request['source'] ?></p>
                </div>
                <div class="col-sm-3">
                    <label>Created At: </label>
                    <p><?php echo date('dS M y  -  h:i:s A', strtotime($request['createdAt'])) ?></p>
                </div>
                <div class="col-sm-3">
                    <label>Status: </label>
                    <p><?php echo $request['status'] ?></p>
                </div>
            </div>
            
            <div class="row followup-view">
                <div class="col-sm-12">
                    <h4>Params</h4>
                </div>
                <?php
                    $requestParams = json_decode($request['params'], true);
                    foreach($requestParams['data'] as $key=>$value) {
                        if($key === 'password') {
                            $value = '**********';
                        }
                        echo sprintf('<div class="col-sm-4">%s</div><div class="col-sm-8">%s</div>', $key, $value);
                    }
                ?>
            </div>
                <?php
                $logLevel['INFO'] = '<span class="badge badge-info">INFO</span>';
                $logLevel['WARN'] = '<span class="badge badge-dark">WARN</span>';
                $logLevel['FATAL'] = '<span class="badge badge-danger">FATAL</span>';
                $logLevel['ERROR'] = '<span class="badge badge-danger">ERROR</span>';
             
                ?>
                
                
            <div class="table-view">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tag</th>
                            <th>Log Level</th>
                            <th>Message</th>
                            <th>Created At</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($logs as $singleLog) { ?>
                        <tr>
                            <td><?php echo $singleLog['id'] ?></td>
                            <td><?php echo $singleLog['tag'] ?></td>
                            
                            <td role="cell"><?php echo isset($logLevel[$singleLog['logLevel']]) ? $logLevel[$singleLog['logLevel']] : $singleLog['logLevel'] ?></td>
                            
                            <td><?php echo $singleLog['message'] ?></td>
                            <td><?php echo $singleLog['createdAt'] ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            
            
     </div>       
            
    
        </main>
    </div>
</div>


<?php include_once __DIR__ . '/./../layout/script.phtml' ?>

// copy to clipbord
<script>function CopyToClipboard(containerid) {
  if (document.selection) {
    var range = document.body.createTextRange();
    range.moveToElementText(document.getElementById(containerid));
    range.select().createTextRange();
    document.execCommand("copy");

  } else if (window.getSelection) {
    var range = document.createRange();
    range.selectNode(document.getElementById(containerid));
    window.getSelection().addRange(range);
    document.execCommand("copy");
  }
}

</script>
    
<?php include_once __DIR__ . '/./../layout/footer.phtml'; ?>